### ISSUE TITLE
Adding more platforms and multiple sonos systems

### ISSUE THREAD

**Issue by kolakub** [brian-su/homebridge-sonos-so-simple#1]
First off - thanks for the plugin. It’s great to be able to control the Arc and Beam by voice and that you can trigger voice enhancement and night mode.

Unfortunately every time I need to restart my homebridge the plugin connects with other speakers of mine (one, sub, play 5). I need to do several restarts to connect it with the Arc again. Is there anyway that you could have it only recognize and Arc or Beam.

Also, any chance you could add multiple platforms for those that have more than one Arc or Beam?

Thanks in advance.

**Comment by Maykel1969** [comment]
Same issue here.
I need several restarts to select the Arc again. Sometimes I get the sub instead.
For the rest this plugin is exactly what I was looking for!
Keep up the good work!

**Comment by brian-su** [comment]
Hopefully I’ll get a chance to look at this over the next day or two. I’ve only got the Beam as my only Sonos product so hadn’t tested with multiple devices. Shouldn’t be too difficult to fix!

**Comment by brian-su** [comment]
Just published an update that *hopefully* should fix this. Slightly flying blind as I only have the Beam as my only device but I reckon this should work. 

I've also set the plugin to default to only adding the Beam and or Arc to homebridge. There is a switch to override this in settings but I've never tested it with anything other than my Beam. 

If someone with multiple devices wants to install the update and let me know what the result is that'd be great. Once it's confirmed that the update fixes the issue I'll close it off.

**Comment by Maykel1969** [comment]
Hi,
I’ve tested the update and it seems to work fine!
I restarted several times and every time I see the Arc and not the sub anymore.
Perfect!
Thanks!

**Comment by kolakub** [comment]
Works for me too. 

Thanks.

**Comment by jfkung** [comment]
Would it be possible to include the Playbar in the soundbar category? Thanks in advance

**Comment by brian-su** [comment]
@jfkung I've added Playbar to the list of discoverable devices but as I don't have one myself I can't know for 100% that it works. Hoping that Sonos have set the device name to be simply Playbar!

If it doesn't work for you open an issue and I'll have a look at it at the weekend! This one has been closed for over a month now.

**Comment by jfkung** [comment]
> @jfkung I've added Playbar to the list of discoverable devices but as I don't have one myself I can't know for 100% that it works. Hoping that Sonos have set the device name to be simply Playbar!
> 
> If it doesn't work for you open an issue and I'll have a look at it at the weekend! This one has been closed for over a month now.

Looking good! Thank you very much. Updated and other devices were removed and playbar was added from cache 
<img width="648" alt="Screen Shot 2021-04-14 at 2 36 57 PM" src="https://user-images.githubusercontent.com/15116654/114784516-2d5d1c80-9d30-11eb-8b12-4c34e73ffa3e.png">
