### ISSUE TITLE
Suggest to add ARC SL support.

### ISSUE THREAD

**Issue by ad2001** [brian-su/homebridge-sonos-so-simple#10]
I have a ARC with no speech support and the plug in is not recognizing it because of the String "ARC SL" is missing. I tried adding "ARC SL" to my local homebridge and the plugin starts working with the soundbar. Not sure if there are more variants to names .. also wonder if doing prefix match is a better solution

https://github.com/brian-su/homebridge-sonos-so-simple/blob/641a189bbb30969f17ee04f2bed519b6831520d3/src/platform.ts#L16

**Comment by brian-su** [comment]
Just published an update to the plugin. I think it should fix your issue. Let me know how it goes!
