### ISSUE TITLE
Control volume with 2 pushbuttons?

### ISSUE THREAD

**Issue by Maykel1969** [brian-su/homebridge-sonos-so-simple#2]
I really like the simplicity of this plugin, exactly what I was looking for, owning just an Arc and a Sub.

But there is one feature that in my opinion would be great to add.
There are two options to control the volume, a fan and a lightbulb.
The problem is that you can not use 2 physical pushbuttons because you can only set fixed values and not steps of x% up/down.
Would it be possible to add a third option having 2 pushbuttons to control the volume in small steps?

This gives for example the opportunity to control volume with 2 philips hue smart buttons. I want to stick 2 of these buttons to my coffee table to control volume if the tv remote control is gone AGAIN. :-)

**Comment by brian-su** [comment]
Happy to add this! It's actually something I'd wondered about myself.

Only problem is that I'm not sure it's actually possible in the Home app? I haven't seen any other homebridge plugins offer an increment/decrement button in this way. I've had a bit of a dig around the homebridge API docs and can't see anything obvious.

If you know of a plugin that does what you've got in mind, let me know and I'll have a dig around the code to see how it could be implemented here. 

Quite new to homebridge development so still very much make it up as I go along!

**Comment by Maykel1969** [comment]
You could add 2 additional switches that turn off automatically after a few millisecs. You can then connect them to physical switches the way you want to.

Setting the percentage of volume is something I do not know much about. Can you read the current volume and simply increment or decrement with x% before you send it back?

I’m quite new to homebridge as well :-)

**Comment by addisonjames** [comment]
Not sure if this is helpful but I added a fan to my homebridge and it only allows me to select preset speeds (33%, 66%, 100%). If that's what you're wondering

**Comment by brian-su** [comment]
closed with the release of 0.3.0
