### ISSUE TITLE
Input change event as trigger for volume automation

### ISSUE THREAD

**Issue by sgraystar** [brian-su/homebridge-sonos-so-simple#30]
Thanks for the plugin, in my setup I use one Arc+sub with a Samsung TV which works perfectly.

One irritation I have has nothing to do with your plugin, but the volume of my usual TV channels is significantly different to my usual music sources which means a manual adjustment every time I change input. 

I use a separate plugin for the TV so tried a "TV on/off" trigger which initially works, but generates too many false triggers.

Is there a Sonos event that could be used to trigger an automation when the input source changes?

**Comment by brian-su** [comment]
Thanks for lovely comments! I made this project just for myself, so I'm always pleasantly surprised and glad to hear my wee plugin is useful to others too! 

Just so that I fully understand you; when you say change the input, is that turning the tv off and then airplaying music to the Sonos? Or is it changing input on the tv from Tv/Firestick etc to Spotify app? Or something else? What's the process? 

To be totally honest, I'm not sure if there is an event like that. But what I could do, is ship a test version of the app to npm, that way it won't trigger updates for everyone, but it means you can select that specific version to install. Inside that update I can just log every event from the device to the console. Then we can see if there's anything that pops up.

Fwiw, the plug-in uses [this](https://github.com/bencevans/node-sonos/tree/master/docs) package to talk to the devices. But I'm not sure there's much documentation to say that there's an event that suits your needs.

**Comment by sgraystar** [comment]
Thanks for the info. This is going beyond 'simple' so feel free to close the issue. I'll put it on my to-do list to investigate a PR.
Cheers

For background my use cases are pretty straightforward:
Play music on the Arc via sonos app (volume set for music), TV connected via HDMI (Sonos app setting TV Autoplay active), turn on the TV, sonos source automatically changes to TV but the volume remains unchanged. I would like to automate a volume change.
The reverse is also true:
Watch TV (volume set for TV), turn off TV, play music via Sonos app (app popup prompt that this will change source from TV), music starts but volume remains unchanged.

The node-sonos package has an 'Event: AVTransport' and example transportEvent.js which may show the source change.
Their Issue 148 gives some background info for the Playbar which may be used to distinguish TV mode from other sources.[https://github.com/bencevans/node-sonos/issues/148#issuecomment-267769917](url)

**Comment by brian-su** [comment]
Hmm, this might be a tad easier than I thought it would be. I need to think it through a bit more so I don't miss any edge cases. But I have an initial hacked together attempt. I'll see if I have more time to look at it properly over the weekend. 


https://github.com/brian-su/homebridge-sonos-so-simple/tree/input-switch-preserve-volume

**Comment by sgraystar** [comment]
Nice!! That looks like it should do it.
Apologies but I'm away from home so cannot test for a couple of weeks. One suggestion would be to confirm validity of currentVolume before making any changes in audioSwitch.ts (e.g. if it is zero then people are going to raise bug reports).
I know from past experience ripping mp3s that private music libraries do not always have the correct metadata, so if the URI is available it is a more robust basis for the decision.

**Comment by sgraystar** [comment]
Thanks Brian. This is working for me if I play a radio-tv-radio because the URIs do not change, same with a track-tv-track, so the basis is OK. It does not work if I am using a playlist and skip to the next song as is causes the URI to change.

I don't agree with the code comment LOL, but instead of using the whole URI my suggestion would be to parse for a keyword within the URI string e.g. 'htastream' to determine the source is TV.
This approach would also work for major sources like 'spotify' etc.
Alternatively, a simple check suggests you may be able to parse the URI up to the first colon ':' to obtain an unchanging URI root that identifies different source types.

If you decide to support remembering the volume for multiple sources then you could get users to define keywords in the config (beyond most plug-and-play users?), or try and pre-populate with a number of more common sources (if you can find such a list). As new sources arise this would always be subject to change, but you could wait for requests before spending too much time on the topic.

**Comment by sgraystar** [comment]
I have changed my mind, the simplest approach appears to be to use the beginning of the URI
`const inputUri = data.CurrentTrackMetaDataParsed.uri.split(":")[0];`

If further breakdown is required in future you could investigate  keywords.

The homebridge way of storing persistent data would be to use accessory.context.audioInputVolumes and api.updatePlatformAccessories. I have used the accessory context to store info but have not looked at updating so will need to investigate a little more.

**Comment by justinshuls** [comment]
Does this expose a button to switch back to TV audio from playing music, looking for a shortcut to that? Tia!

**Comment by sgraystar** [comment]
Instead of using a file to store persistent data, is it as easy as storing under deviceDetails ?
` this.audioInputVolumes = deviceDetails.audioInputVolumes;`

The advantage over accessory.context is that if someone is managing multiple speakers then it is possible they are used at different volumes per speaker/environment.
It is also possible to clean out the saved history by clearing the accessory cache.

**Comment by sgraystar** [comment]
Sorry for the untidy post. Storing the string of saved inputs under DeviceDetails appears to be viable as you can watch the construction of audioInputVolumes as the source changes, and see separate info per speaker.

models.ts
`export type DeviceDetails = {
    ...
    SavedInputVolumes: string;`

platformAccessory.ts
`new AudioSwitchService(manager, deviceDetails.SavedInputVolumes, logger);`

audioSwitch.ts
`    constructor(sonosDevice: SonosDeviceManager, savedInputVolumes: string, logger: SonosLogger) {
        this.savedInputVolumes = savedInputVolumes;
        if (this.savedInputVolumes) {
            this.audioInputVolumes = JSON.parse(this.savedInputVolumes);
        }`

What I cannot work out (JS/TS is def not my area) is how to save audioInputVolumes as a string back under DeviceDetails, such as something like having audioSwitch.ts return the string and platformAccessory.ts saving the persistent info:
`deviceDetails.SavedInputVolumes = new AudioSwitchService(manager, deviceDetails.SavedInputVolumes, logger);`

**Comment by brian-su** [comment]
> What I cannot work out (JS/TS is def not my area) is how to save audioInputVolumes as a string back under DeviceDetails, such as something like having audioSwitch.ts return the string and platformAccessory.ts saving the persistent info: `deviceDetails.SavedInputVolumes = new AudioSwitchService(manager, deviceDetails.SavedInputVolumes, logger);`

Finally getting time to come back to this now! Life got in the way. The issue with saving the context back to the accessory in homebridge was the original reason I chose the messy json file approach. Thanks for the nudge! I've managed to get that to work via callbacks registered when creating the accessory in homebridge. 

I still can't get the audio switching logic right but I think I need to spend some proper time actually debugging through it. Hopefully I'll manage that next week.

**Comment by brian-su** [comment]
> Does this expose a button to switch back to TV audio from playing music, looking for a shortcut to that? Tia!

Short answer, no. 

Doesn't Sonos auto switch the audio if you're on tv and start playing music/radio/whatever to it instead?

**Comment by sgraystar** [comment]
Is the complicated model.ts needed? Simply reinstating some of the push logic you had before and saving the data back under this.details.AudioInputVolumes before making the call to updatePlatformAccessories([existingAccessory] seems to do the job?

audioSwitch.ts
`
    private saveVolumeForPreviousInput(volume: number, inputUri: string | undefined) {
        if (inputUri === undefined) return;
        const inputIndex = this.details.AudioInputVolumes.findIndex((x) => x.InputUri === this.previousUri);
        const updatedInputVolume = { InputUri: inputUri, Volume: volume } as AudioInputModel;
        if (inputIndex === -1) {
            this.details.AudioInputVolumes.push(updatedInputVolume);
        } else {
            this.details.AudioInputVolumes[inputIndex] = updatedInputVolume;
        }
        /* this.details.UpdateAudioVolumes(this.details.UUID, updatedInputVolume, this.details.AudioInputVolumes); */
        return;
    }
`

**Comment by brian-su** [comment]
> Is the complicated model.ts needed? Simply reinstating some of the push logic you had before and saving the data back under this.details.AudioInputVolumes before making the call to updatePlatformAccessories([existingAccessory] seems to do the job?

I think it is yes. So the previous logic worked while the homebridge was running but would lose all details once you reboot or if the homebridge crashes etc. All that logic did was save the details in memory on the accessory object. The homebridge platform itself needs to have the details saved against the accessory. Which AFAIK can't be done by the accessory itself (at least I couldn't find anything in the documentation to suggest there was a method available for this). 

That's why I came up with the callback method for the accessory to call back out at the platform level where the details can be saved. 

I think I've got it all working now I just want to test it a bit to make sure. Or I might even just whack it out as a Beta version so that if you want to you can install it without me buggering up other users set ups if there's a bug.

**Comment by sgraystar** [comment]
I downloaded a copy of the branch and installed on a separate homebridge, it appears to be working well. Thanks.

**Comment by brian-su** [comment]
Finally got around to releasing this properly. It's live now. Closing this now.
