### ISSUE TITLE
API Endpoints and Device Support

### ISSUE THREAD

**Issue by kiwisapo** [brian-su/homebridge-sonos-so-simple#52]
Firstly, a huge thank you for developing this plugin.   
It was exactly what I needed, a simple and logical solution that just works.

While it's nearly perfect for my needs, I would love to see additional endpoints for Night Mode and Speech Enhancement.

Also, I can confirm that you can include Playbase as a supported soundbar.  
I modified the constants.js file to include PLAYBASE as an additional SOUNDBAR_NAMES variable and after restarting Homebridge, everything worked perfectly.  

Again, thank you for all your effort, it fantastic being able to control just my Arc and Playbase without exposing all my other speakers!!

**Comment by brian-su** [comment]
Thanks for the kind words. Both of these seem reasonable doable at first glance. I'll have a bash at it when I get some free time over the next few days.

**Comment by brian-su** [comment]
Now deployed as part of versions 0.5.0/0.5.1
