### ISSUE TITLE
"old" Arc was here, New Arc Ultra is not showing up

### ISSUE THREAD

**Issue by Matt-uSk** [brian-su/homebridge-sonos-so-simple#76]
"old" Arc was here, juste replaced it with New Arc Ultra

Can't get the arc ultra in homebridge

```
Show the Homebridge logs here, remove any sensitive information.

[11/9/2024, 10:49:46 PM] [SonosSoSimplePlatform] Got All Devices
```

**Plugin Config:**

```json
        {
            "muteSwitch": true,
            "soundbarsOnly": true,
            "roomNameAsName": false,
            "volume": "bulb",
            "volumeControlEndpoints": false,
            "preserveVolumeOnInputSwitch": true,
            "platform": "SonosSoSimplePlatform"
        }
```

**Environment:**

* **Plugin Version**: 0.5.1
* **Homebridge v1.8.5]
* **Node.js Version**: 20.18.0
* **NPM Version**:i dont know
* **Operating System**: proxmoxx

**Comment by Matt-uSk** [comment]
After changing "soundbarsOnly" to false, the Arc ultra is here.

**Comment by Matt-uSk** [comment]
I dont know how to contribute but i think if you add "Arc Ultra" to src/models/constants.ts it should be fine

**Comment by brian-su** [comment]
Thanks for your PR Matt. Looks grand, I've got a bunch of dependant package upgrades that I've been ignoring. I'm going to look at these tonight or tomorrow and bump the version so the deploy pipeline will push out the update.
