### ISSUE TITLE
Plugin not working anymore after months of troublefree operation

### ISSUE THREAD

**Issue by Maykel1969** [brian-su/homebridge-sonos-so-simple#8]
![4A820EE8-3DE7-4306-8D32-744D99B03F95](https://user-images.githubusercontent.com/77012346/133905412-08f769b9-b397-4765-b82d-0d9c7b091d68.jpeg)

why is it not working anymore?
I love the simplicity of this plugin!

**Comment by Maykel1969** [comment]
Fixed!
Disabled the plugin and then enabled it again.
Problem solved but no idea what I fixed :-)

**Comment by brian-su** [comment]
Closing the issue as it hasn't reappeared
