### ISSUE TITLE
Pull device name rather than model?

### ISSUE THREAD

**Issue by mylesagray** [brian-su/homebridge-sonos-so-simple#9]
**Is your feature request related to a problem? Please describe:**

Hi there! 

I love this plug-in, the simplicity is fantastic! There is one gripe I have however, I want to use it in every room in the house, which would be fine except the name of the devices in HomeKit are the models of the speakers, rather than the speaker names.

I have over 15 speakers in my house, many of which are the same model :)

**Describe the solution you'd like:**

A toggle to choose whether to expose devices by their name in the Sonos app or their model.

**Comment by brian-su** [comment]
Hi Myles, 

Happy to make that change, but struggling to see exactly how to make it. I only have the single Sonos Beam as my sole device to be controlled by my plug-in so it makes debugging and testing for wider setups a tad difficult!

Where are you changing the name in the Sonos app? As far as I can see the only option is to change the room name which in my case would be Living Room. Is that the name you want to surface via the plugin? Currently the plugin sets the name in Homebridge to the 'displayName' that is returned from the Sonos API. That just happens to be the model name it seems. The only other option I can see that makes sense from the API is room name. But then multiple devices in the same room would clash and break the plugin. 

Hopefully you can shed some light. Other option, is I'm happy to ship a version of the plugin with a debug toggle and have it spit out the device details to the console and maybe then with it outputting multiple devices to the logs you can help point me in the right direction!

**Comment by mylesagray** [comment]
Hey Brian!

Thanks for taking the time to look at this.

So you’re right, I would expect them to be listed as the Room Name, and the reason why is that you cannot (I believe) have more than one Sonos “system” per room - say you have an Arc + Sub + two Fives, that’s just the “Living Room”.

In the bedroom, maybe you have a Symphonisk lamp and two Fives for whatever reason? Well the Sonos app will not actually allow you to do that, you can indeed have either your Symphonisk or Fives in a room called “Bedroom”, but you will be made to set up another “room” for whatever is left.

So it’s not like you can have multiple groups of say Sonos stereo pairs in one “room” as Sonos sees it, you can of course physically have more in one room, but the app will force you to name them differently - like “Bedroom Fives” and “Bedroom Lamp”.

If you want to ship a version with the debug toggle, it will probably make it easier for you to see what’s going on.

See below for an example of how one of my rooms with a few speakers in is actually just displayed in the Sonos app, even though it’s a composite of multiple devices:

---------------------------------
Playbar: Gym Sonos
Serial Number: xxx
Sonos OS: S2
Version: 14.0 (build 67125031)
Hardware Version: 1.9.1.10-2.2
Series ID: A100
IP Address: xxx
Audio In: 
WM: 1
OTP: 
---------------------------------
Play:1: Gym Sonos (RS)
Serial Number: xxx
Sonos OS: S2
Version: 14.0 (build 67125031)
Hardware Version: 1.20.1.6-2.2
Series ID: A200
IP Address: xxx
WM: 2
---------------------------------
Play:1: Gym Sonos (LS)
Serial Number: xxx
Sonos OS: S2
Version: 14.0 (build 67125031)
Hardware Version: 1.20.1.6-2.2
Series ID: A200
IP Address: xxx
WM: 2
————————————————

**Comment by mylesagray** [comment]
Hey Brian!

Thanks for taking the time to look at this.

So you’re right, I would expect them to be listed as the Room Name, and the reason why is that you cannot (I believe) have more than one Sonos “system” per room - say you have an Arc + Sub + two Fives, that’s just the “Living Room”.

In the bedroom, maybe you have a Symphonisk lamp and two Fives for whatever reason? Well the Sonos app will not actually allow you to do that, you can indeed have either your Symphonisk or Fives in a room called “Bedroom”, but you will be made to set up another “room” for whatever is left.

So it’s not like you can have multiple groups of say Sonos stereo pairs in one “room” as Sonos sees it, you can of course physically have more in one room, but the app will force you to name them differently - like “Bedroom Fives” and “Bedroom Lamp”.

If you want to ship a version with the debug toggle, it will probably make it easier for you to see what’s going on.

See below for an example of how one of my rooms with a few speakers in is actually just displayed in the Sonos app, even though it’s a composite of multiple devices:

![Screenshot 2022-02-18 at 11 02 01](https://user-images.githubusercontent.com/609356/154671005-c4640783-6040-4d7f-80ec-0b833f1f0dc3.png)

    ---------------------------------
    Playbar: Gym Sonos
    Serial Number: xxx
    Sonos OS: S2
    Version: 14.0 (build 67125031)
    Hardware Version: 1.9.1.10-2.2
    Series ID: A100
    IP Address: xxx
    Audio In: 
    WM: 1
    OTP: 
    ---------------------------------
    Play:1: Gym Sonos (RS)
    Serial Number: xxx
    Sonos OS: S2
    Version: 14.0 (build 67125031)
    Hardware Version: 1.20.1.6-2.2
    Series ID: A200
    IP Address: xxx
    WM: 2
    ---------------------------------
    Play:1: Gym Sonos (LS)
    Serial Number: xxx
    Sonos OS: S2
    Version: 14.0 (build 67125031)
    Hardware Version: 1.20.1.6-2.2
    Series ID: A200
    IP Address: xxx
    WM: 2

**Comment by brian-su** [comment]
Ok, I've published an updated version with the option to use the room name as the display name instead. It's an option in the config file. Let me know if that sorts your issue out! 😄

**Comment by mylesagray** [comment]
Thanks so much for the change @brian-su!

It seems something it messed up though:

```
[2/28/2022, 2:32:01 PM] ---
[2/28/2022, 2:32:01 PM] ====================
[2/28/2022, 2:32:01 PM] ERROR LOADING PLUGIN homebridge-sonos-so-simple:
[2/28/2022, 2:32:01 PM] Error: Cannot find module './settings'
Require stack:
- /homebridge/node_modules/homebridge-sonos-so-simple/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-sonos-so-simple/src/index.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/src/plugin.ts:197:93)
    at PluginManager.initializeInstalledPlugins (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:131:22)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:5)
[2/28/2022, 2:32:01 PM] ====================
```

I had a look at the code in your `name-change` branch, but it doesn't look like that touched anything near settings?

**Comment by brian-su** [comment]
Hmm, so I've played around and I'm not getting anything like that. Sorry to ask *the* question, but have you tried uninstalling it, rebooting hombridge and reinstalling it? I tested it both on my Pi and locally and didn't see any errors like that 😕

**Comment by mylesagray** [comment]
Well, it appears that updating to 0.1.4 - not sure if you pushed something else? - fixed it!

Interestingly, there appears to be a behaviour that each Sonos device is exposing itself as "the room" in question.

So - in my Living room I have an Arc, a Sub and 2x Fives in a 5.1 group - but the plugin exposes each device as a distinct entity, when in fact they should be displayed as a single entity for the entire group.

I had been using another plugin (homebridge-sonos-multiroom) that uses the same library as you, and does do zone grouping, but not volume control, using that lib: https://github.com/lukasroegner/homebridge-sonos-multiroom/blob/5b813783f0cd2070e5cb8b546859cfdc10d159c6/src/sonos-multiroom-platform.js#L85-L120

I appreciate that this may be out of scope for this plugin, so understand if it's not something you want to pursue.

**Comment by brian-su** [comment]
I think this should all be fixed, if you're still using the plugin! 

Feel free to reopen if needed. Sorry for the delay!
